modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]] 
modId="skyships" 
version="${file.jarVersion}"
displayName="Sky Ships"
authors="DivineAspect,SkySom"
description='''
'''

[[dependencies.skyships]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyships]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
